esphome:
  name: esphome-sw35xx
  includes:
    - esphome-sw35xx.h
  libraries:
    - "Wire"
    - "https://github.com/happyme531/h1_SW35xx#1.0.1"

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption: 
    key: !secret esp_api_key

ota:
  password: !secret esp_ota_password

wifi:
  ssid: !secret wifi_ssid
  password:  !secret wifi_password
  fast_connect: true
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Sw35Xx Fallback Hotspot"
    password: !secret esp_ota_password

captive_portal:

sensor:
  - platform: custom
    lambda: |-
      auto sw35xxNumberSensors = new ESPHomeSW35xxNumberSensors(D6,D7);
      //Uncomment the following lines to set the max current in milliamp if you like. 
      //Fixed: 5v, 9v, 12v, 15v, 20v / PPS: pps1, pps2
      //Please note that the max current is limited by the board you are using.
      //If you set a higher value, the chip will likely overheat. Be careful!
      //sw35xxNumberSensors->setMaxCurrentsFixed(5000,5000,5000,5000,5000);
      //sw35xxNumberSensors->setMaxCurrentsPPS(5000,5000);
      App.register_component(sw35xxNumberSensors);
      return {sw35xxNumberSensors->inputVoltageSensor,sw35xxNumberSensors->outputVoltageSensor,sw35xxNumberSensors->outputCurrent1Sensor,sw35xxNumberSensors->outputCurrent2Sensor};
    sensors:
      - name: "SW35xx Input Voltage"
        id: inputVoltage
        unit_of_measurement: "V"
        accuracy_decimals: 1
        icon: "mdi:flash"
      - name: "SW35xx Output Voltage"
        id: outputVoltage
        unit_of_measurement: "V"
        accuracy_decimals: 2
        icon: "mdi:flash"
      - name: "SW35xx Output Current 1"
        id: outputCurrent1
        unit_of_measurement: "A"
        accuracy_decimals: 3
        icon: "mdi:flash"
      - name: "SW35xx Output Current 2"
        id: outputCurrent2
        unit_of_measurement: "A"
        accuracy_decimals: 3
        icon: "mdi:flash"
  
  
text_sensor:
  - platform: custom
    lambda: |-
      auto sw35xxTextSensor = new ESPHomeSW35xxTextSensor();
      App.register_component(sw35xxTextSensor);
      return {sw35xxTextSensor};
    text_sensors:
      - name: "SW35xx Fast Charge Type"
        id: fastChargeType

# Builtin LED for nodemcu
light:
  - platform: status_led
    name: "Nodemcu Status LED"
    pin:
      number: GPIO16
      inverted: true
# Boot button for nodemcu
binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: "Nodemcu Boot Button"
    filters:
      - invert:
